move to root directory

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,26 +29,20 @@ jobs:
           draft: false
           prerelease: false
 
-      - name: Navigate to 'res/release'
-        run: cd res/release || exit 1
-
-      - name: List contents of 'res' directory
-        run: ls -l res
-
       - name: List contents of 'res/release' directory
-        run: ls -l res/release
+        run: ls -l release
 
-      - name: Navigate to 'res/release'
-        run: cd res/release || { echo "Directory not found"; exit 1; }
+      - name: Navigate to 'release'
+        run: cd release || { echo "Directory not found"; exit 1; }
 
       - name: Check current directory after cd
         run: |
           pwd
           ls -l
-      
+
       - name: Tree Directory
         run: |
-          tree -a . -I ".git|res/Old CVs/*"
+          tree -a . -I ".git|res/*"
 
       - name: Upload Release Asset
         env:
